engines:
  fixme:
    enabled: false
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      - file_extensions: "php"
      - standard: ["PSR1", "PSR2"]

exclude_paths:
- .git/**/*
- vendor/**/*
